/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * EqFast_LeftStart2V20.cpp
 *
 * Code generation for function 'EqFast_LeftStart2V20'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Fast_MPCV20_form_Step2.h"
#include "EqFast_LeftStart2V20.h"

/* Function Definitions */
void EqFast_LeftStart2V20(const real_T in1[2], const real_T in2[2], real_T Cpx1,
  real_T Cpy1, const real_T in5[3], const real_T in6[3], real_T beq[76])
{
  real_T t2;
  real_T t3;
  real_T t4;

  /* EQFAST_LEFTSTART2V20 */
  /*     [AEQ,BEQ] = EQFAST_LEFTSTART2V20(IN1,IN2,CPX1,CPY1,IN5,IN6) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.0. */
  /*     06-Aug-2023 21:20:33 */
  t2 = Cpx1 - in5[2];
  t3 = Cpy1 + in6[2];
  t4 = Cpy1 - in6[2];
  memset(&beq[0], 0, sizeof(real_T) << 6);
  beq[64] = in1[0];
  beq[65] = in1[1];
  beq[66] = in2[0];
  beq[67] = in2[1];
  beq[68] = t2;
  beq[69] = t2;
  beq[70] = t2;
  beq[71] = t2;
  beq[72] = t3;
  beq[73] = t4;
  beq[74] = t3;
  beq[75] = t4;
}

/* End of code generation (EqFast_LeftStart2V20.cpp) */
