function Rdot = GeneratedPelvisRotdot(base,dbase)
%GENERATEDPELVISROTDOT
%    RDOT = GENERATEDPELVISROTDOT(PHI,THETA,PSI,DRX,DRY,DRZ)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Feb-2020 16:18:56


psi = base(1);
theta = base(2);
phi = base(3);

drz = dbase(1);
dry = dbase(2);
drx = dbase(3);

t2 = cos(psi);
t3 = sin(psi);
t4 = cos(phi);
t5 = sin(theta);
t6 = cos(theta);
t7 = sin(phi);
Rdot = reshape([-dry.*t2.*t5-drz.*t3.*t6,-dry.*t3.*t5+drz.*t2.*t6,-dry.*t6,drx.*t3.*t7-drz.*t2.*t4+drx.*t2.*t4.*t5+dry.*t2.*t6.*t7-drz.*t3.*t5.*t7,-drx.*t2.*t7-drz.*t3.*t4+drx.*t3.*t4.*t5+dry.*t3.*t6.*t7+drz.*t2.*t5.*t7,drx.*t4.*t6-dry.*t5.*t7,drx.*t3.*t4+drz.*t2.*t7-drx.*t2.*t5.*t7+dry.*t2.*t4.*t6-drz.*t3.*t4.*t5,-drx.*t2.*t4+drz.*t3.*t7-drx.*t3.*t5.*t7+dry.*t3.*t4.*t6+drz.*t2.*t4.*t5,-drx.*t6.*t7-dry.*t4.*t5],[3,3]);
