function jaco = GenrateEulerDiffToOmega(theta)
%GENRATEEULERDIFFTOOMEGA
%    JACO = GENRATEEULERDIFFTOOMEGA(ROTZ,ROTY,ROTX)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Dec-2019 14:10:52
rotz = theta(1);
roty = theta(2);
rotx = theta(3);

t2 = cos(rotz);
t3 = cos(roty);
t4 = sin(rotz);
jaco = reshape([0.0,0.0,1.0,-t4,t2,0.0,t2.*t3,t3.*t4,-sin(roty)],[3,3]);
