function [f,Jf] = ComputeEllipseInfo(xe,xr,xc,ye,yr,yc,t,lambda,a,b)
%COMPUTEELLIPSEINFO
%    [F,JF] = COMPUTEELLIPSEINFO(XE,XR,XC,YE,YR,YC,T,LAMBDA,A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Aug-2023 19:57:46

t2 = cos(t);
t3 = sin(t);
t4 = yc-ye;
t5 = xc-xe;
t6 = 1.0./b.^2;
t7 = t2.*t4;
t13 = t3.*t5;
t8 = t7-t13;
t9 = 1.0./a.^2;
t10 = t2.*t5;
t11 = t3.*t4;
t12 = t10+t11;
t14 = t3.*t6.*t8.*2.0;
t22 = t2.*t9.*t12.*2.0;
t15 = t14-t22;
t16 = t2.*t3.*t6.*2.0;
t17 = t16-t2.*t3.*t9.*2.0;
t18 = t2.^2;
t19 = t3.^2;
t20 = t2.*t6.*t8.*2.0;
t21 = t3.*t9.*t12.*2.0;
f = [xe.*2.0-xr.*2.0+lambda.*t15;ye.*2.0-yr.*2.0-lambda.*(t20+t21);t6.*t8.^2+t9.*t12.^2-1.0];
if nargout > 1
    t23 = -t20-t21;
    Jf = reshape([lambda.*(t6.*t19.*2.0+t9.*t18.*2.0)+2.0,-lambda.*t17,t15,-lambda.*t17,lambda.*(t6.*t18.*2.0+t9.*t19.*2.0)+2.0,t23,t15,t23,0.0],[3,3]);
end
